### ISSUE TITLE
用平台后缀名文件的方式同构组件

### ISSUE THREAD

**Issue by Darmody** [remaxjs/remax-recycle-view#15]
https://github.com/remaxjs/remax-recycle-view/blob/master/src/remax.tsx#L2-L17

**Comment by yesmeck** [comment]
还有要保留 jsx？

**Comment by ahungrynoob** [comment]
@Darmody 这个问题 可以通过环境变量在编译时生成目标平台的代码吧？webpack可以删除dead code

如果采用后缀名的方式，个人不是很喜欢一样的代码写多遍

**Comment by ahungrynoob** [comment]
v1.0.2
