### ISSUE TITLE
微信真机滚动时抖动

### ISSUE THREAD

**Issue by dominicleo** [remaxjs/remax-recycle-view#20]
![image](https://user-images.githubusercontent.com/16660567/82774074-5eadcf00-9e76-11ea-8676-d0dc043b78ba.gif)

**Comment by Darmody** [comment]
试试这个 https://github.com/remaxjs/remax/pull/989  的 remax 包，还有没有这个问题

**Comment by dominicleo** [comment]
同样有这个问题

**Comment by ahungrynoob** [comment]
稍等 我看下

**Comment by ahungrynoob** [comment]
https://github.com/dominicleo/remax-virtual-list @dominicleo 这个库还会存在闪烁问题吗

**Comment by dominicleo** [comment]
remax-window
remax-recycle-view
remax-virtual-list
这三个库在微信平台下都会抖动

**Comment by dominicleo** [comment]
remax 的问题，已经处理了
https://github.com/remaxjs/remax/pull/1053
