### ISSUE TITLE
需求：建议增加一个属性，用于将列表滚动到指定元素的位置

### ISSUE THREAD

**Issue by Rennix09** [remaxjs/remax-recycle-view#22]
我目前正使用remax-recycle-view来做picker，列表数据很长。我通过后端接口得知用户选中了列表中的某一项，因此我在itemsRender处，已为该项设置了高亮的css样式。
现在遇到的问题是，列表总是从index=0的位置向用户进行展示，这可能并不适合我现在的场景。
我希望能将该选中项的index传入remax-recycle-view组件，以让remax-recycle-view组件自动滚动到我选中项所在的位置，用户不需每次都要从列表顶部开始滚动就可以轻松找到自己之前选中的是哪一项。
望采纳。

**Comment by yesmeck** [comment]
@ahungrynoob 有空看看啊

**Comment by ahungrynoob** [comment]
> @ahungrynoob 有空看看啊

我看看

**Comment by ahungrynoob** [comment]
v1.1.0

**Comment by Rennix09** [comment]
@yesmeck  @ahungrynoob  使用scrollTopByIndex设置初始滚动位置似乎有点问题。
我使用下面的命令安装包
```bash
npm i remax-recycle-view@1.1.0
```
运行环境是微信小程序开发者工具。代码如下：
```react
import * as React from 'react'
import { View } from 'remax/wechat'
import RecycleView from 'remax-recycle-view/lib/index'
const mockData: { height: number; [key: string]: any }[] = [];
// 生成2000个元素
for (let i = 0; i < 2020; i++) {
  mockData.push({
    height: 100,
    text: `row ${i}`,
  });
}

export default () => {
  return (
    <View>
      <RecycleView
        style={{height:'100vh'}}
        data={mockData}
        // 期待滚动到mockData中index=100的位置，实际上滚动到了index=235的位置
        scrollTopByIndex={100}
        renderItem={({ text, __index__ }) => {
          return (
            <View style={{ backgroundColor:'white', fontWeight:'bold', color: 'red', height: '100%' }}>{text}</View>
          );
        }}
      />
    </View>
  );
};
```
期待运行结果：
![image](https://user-images.githubusercontent.com/26057167/92987200-fcdfa680-f4f2-11ea-8a5e-0f5dbe0e6495.png)

实际运行结果：
![image](https://user-images.githubusercontent.com/26057167/92987180-cefa6200-f4f2-11ea-8c94-98833da7a9ea.png)

望修复，万分感谢！

**Comment by ahungrynoob** [comment]
v1.1.1
