### ISSUE TITLE
用后缀名的方式区分平台

### ISSUE THREAD

**Issue by yesmeck** [remaxjs/remax-recycle-view#5]
https://github.com/remaxjs/remax-recycle-view/blame/master/src/remax.tsx

目前这种方式会把不同平台的代码都打包进去。用后缀名的方式更好，https://remaxjs.org/guide/one#%E4%BD%BF%E7%94%A8%E6%96%87%E4%BB%B6%E5%90%8D%E5%90%8E%E7%BC%80%E5%8C%BA%E5%88%86%E4%B8%8D%E5%90%8C%E5%B9%B3%E5%8F%B0%E4%BB%A3%E7%A0%81

**Comment by ahungrynoob** [comment]
@yesmeck 
```
if (process.env.REMAX_PLATFORM === 'wechat') {
  console.log('wechat');
}
```
没办法通过这样，在压缩阶段删除代码吗？

**Comment by yesmeck** [comment]
这样也是可以的。

**Comment by ahungrynoob** [comment]
@yesmeck 嗯嗯，目前就是这样的方法，去控制的～

**Comment by yesmeck** [comment]
switch 不知道行不行

https://github.com/remaxjs/remax-recycle-view/blame/master/src/remax.tsx#L49

**Comment by ahungrynoob** [comment]
嗯 我也有这个顾虑 还是改成if保险一点 google了一遍也没找到

**Comment by ahungrynoob** [comment]
抛下结论： 没有google到 亲测 switch case statement 是没法做到删掉dead code的
